name: Scrape SeLoger

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Nom de l'agence"
        required: true
        default: "Expertim immobilier"
      slug:
        description: "Ville slug (ex: versailles-78000)"
        required: true
        default: "versailles-78000"
  schedule:
    - cron: '0 6 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

          - name: Install dependencies & browsers
          run: |
            npm install
            npx playwright install --with-deps chromium        

      - name: Run scraper and show result
        run: |
          echo "📊 Résultat du scraping :" 
          node scraper.js --name "${{ github.event.inputs.name }}" --slug "${{ github.event.inputs.slug }}"
